name: 'Build, Test, and Publish PowerShell Module'
on: [workflow_dispatch]
env:
  MODULE_NAME: 'AzReports'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: russellds/pwsh-module-build@v0
      id: pwshModuleBuild

    outputs:
      preReleaseLabel: ${{ steps.pwshModuleBuild.outputs.preReleaseLabel }}

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: russellds/pwsh-module-test@v0
        with:
          moduleName: ${{ env.MODULE_NAME }}

      - name: Outputs Variables
        shell: pwsh
        run: |
          Write-Host "PreReleaseLabel: ${{ needs.build.outputs.preReleaseLabel }}"

  publishPreview:
    if: contains(needs.build.outputs.preReleaseLabel, 'preview')
    runs-on: windows-latest
    needs: [build, test]
    environment:
      name: preview
    steps:
      - uses: russellds/pwsh-module-publish@v0
        with:
          moduleName: ${{ env.MODULE_NAME }}
          nuGetApiKey: ${{ secrets.PS_GALLERY_API_KEY }}
          testGallery: 'True'

  publishProd:
    if: needs.build.outputs.preReleaseLabel == ''
    runs-on: windows-latest
    needs: [build, test]
    environment:
      name: prod
    steps:
      - uses: russellds/pwsh-module-publish@v0
        with:
          moduleName: ${{ env.MODULE_NAME }}
          nuGetApiKey: ${{ secrets.PS_GALLERY_API_KEY }}
